### ISSUE TITLE
bug creating user john doe

### ISSUE THREAD

**Issue by ghost** [z3nz/my-jsql#1]
anibal@LENOVO:~/my-jsql$ npm run build

> my-jsql@1.5.1 build /home/anibal/my-jsql
> npm run lint; babel src --presets babel-preset-es2015 --out-dir dist --minified --no-comments; npm test

> my-jsql@1.5.1 lint /home/anibal/my-jsql
> eslint src -c .eslintrc.js; eslint test -c .eslintrc.js

src/index.js -> dist/index.js
src/lib/MyJsql.js -> dist/lib/MyJsql.js

> my-jsql@1.5.1 test /home/anibal/my-jsql
> mocha test

  MyJsql
    ✓ assertions (56ms)
    ✓ start (48ms)
    ✓ create db
    ✓ use db
    ✓ create table (332ms)
    ✓ set table
    1) insert John Doe
    2) insert Jane Doe
    3) select John
    4) select only one key
    5) select John and Jane
    6) where condition as string
    7) select John or Jane
    8) update John to Jack
    9) order by first
    10) order by id and first
    11) limit to one
    12) limit and offset by one
    13) select where order by and limit
    14) clear test
    15) delete Jane
    ✓ drop db (202ms)
    ✓ stop

  8 passing (947ms)
  15 failing

  1) MyJsql insert John Doe:
     TypeError: Object.values is not a function
      at dist/lib/MyJsql.js:1:1740
      at MyJsql.each (dist/lib/MyJsql.js:1:5372)
      at MyJsql.i (dist/lib/MyJsql.js:1:1582)
      at Context.<anonymous> (test/test.js:61:10)

  2) MyJsql insert Jane Doe:
     TypeError: Object.values is not a function
      at dist/lib/MyJsql.js:1:1740
      at MyJsql.each (dist/lib/MyJsql.js:1:5372)
      at MyJsql.i (dist/lib/MyJsql.js:1:1582)
      at Context.<anonymous> (test/test.js:74:10)

  3) MyJsql select John:
     Uncaught AssertionError: undefined must be an object
      at Object.isObject (node_modules/unit.js/src/assertions.js:316:20)
      at new ObjectAsserter (node_modules/unit.js/src/asserters/object.js:99:14)
      at UnitJS.module.exports.(anonymous function) [as object] (node_modules/unit.js/src/asserters.js:27:14)
      at Query._callback (test/test.js:94:12)
      at Query.Sequence.end (node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
      at Query._handleFinalResultPacket (node_modules/mysql/lib/protocol/sequences/Query.js:139:8)
      at Query.EofPacket (node_modules/mysql/lib/protocol/sequences/Query.js:123:8)
      at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:279:23)
      at Parser.write (node_modules/mysql/lib/protocol/Parser.js:76:12)
      at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:103:28)
      at readableAddChunk (_stream_readable.js:176:18)
      at Socket.Readable.push (_stream_readable.js:134:10)
      at Pipe.onread (net.js:547:20)

  4) MyJsql select only one key:
     Uncaught AssertionError: undefined must be an object
      at Object.isObject (node_modules/unit.js/src/assertions.js:316:20)
      at new ObjectAsserter (node_modules/unit.js/src/asserters/object.js:99:14)
      at UnitJS.module.exports.(anonymous function) [as object] (node_modules/unit.js/src/asserters.js:27:14)
      at Query._callback (test/test.js:112:12)
      at Query.Sequence.end (node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
      at Query._handleFinalResultPacket (node_modules/mysql/lib/protocol/sequences/Query.js:139:8)
      at Query.EofPacket (node_modules/mysql/lib/protocol/sequences/Query.js:123:8)
      at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:279:23)
      at Parser.write (node_modules/mysql/lib/protocol/Parser.js:76:12)
      at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:103:28)
      at readableAddChunk (_stream_readable.js:176:18)
      at Socket.Readable.push (_stream_readable.js:134:10)
      at Pipe.onread (net.js:547:20)

  5) MyJsql select John and Jane:

      Uncaught AssertionError: 0 must be equivalent to 2
      + expected - actual

      -0
      +2
      
      at NumberAsserter.is (node_modules/unit.js/src/assertions.js:56:20)
      at Query._callback (test/test.js:127:29)
      at Query.Sequence.end (node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
      at Query._handleFinalResultPacket (node_modules/mysql/lib/protocol/sequences/Query.js:139:8)
      at Query.EofPacket (node_modules/mysql/lib/protocol/sequences/Query.js:123:8)
      at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:279:23)
      at Parser.write (node_modules/mysql/lib/protocol/Parser.js:76:12)
      at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:103:28)
      at readableAddChunk (_stream_readable.js:176:18)
      at Socket.Readable.push (_stream_readable.js:134:10)
      at Pipe.onread (net.js:547:20)

  6) MyJsql where condition as string:

      Uncaught AssertionError: 0 must be equivalent to 1
      + expected - actual

      -0
      +1
      
      at NumberAsserter.is (node_modules/unit.js/src/assertions.js:56:20)
      at Query._callback (test/test.js:140:29)
      at Query.Sequence.end (node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
      at Query._handleFinalResultPacket (node_modules/mysql/lib/protocol/sequences/Query.js:139:8)
      at Query.EofPacket (node_modules/mysql/lib/protocol/sequences/Query.js:123:8)
      at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:279:23)
      at Parser.write (node_modules/mysql/lib/protocol/Parser.js:76:12)
      at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:103:28)
      at readableAddChunk (_stream_readable.js:176:18)
      at Socket.Readable.push (_stream_readable.js:134:10)
      at Pipe.onread (net.js:547:20)

  7) MyJsql select John or Jane:

      Uncaught AssertionError: 0 must be equivalent to 2
      + expected - actual

      -0
      +2
      
      at NumberAsserter.is (node_modules/unit.js/src/assertions.js:56:20)
      at Query._callback (test/test.js:153:29)
      at Query.Sequence.end (node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
      at Query._handleFinalResultPacket (node_modules/mysql/lib/protocol/sequences/Query.js:139:8)
      at Query.EofPacket (node_modules/mysql/lib/protocol/sequences/Query.js:123:8)
      at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:279:23)
      at Parser.write (node_modules/mysql/lib/protocol/Parser.js:76:12)
      at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:103:28)
      at readableAddChunk (_stream_readable.js:176:18)
      at Socket.Readable.push (_stream_readable.js:134:10)
      at Pipe.onread (net.js:547:20)

  8) MyJsql update John to Jack:
     TypeError: Object.values is not a function
      at dist/lib/MyJsql.js:1:2248
      at MyJsql.each (dist/lib/MyJsql.js:1:5372)
      at MyJsql.u (dist/lib/MyJsql.js:1:2088)
      at Context.<anonymous> (test/test.js:159:10)

  9) MyJsql order by first:
     Uncaught AssertionError: undefined must be an object
      at Object.isObject (node_modules/unit.js/src/assertions.js:316:20)
      at new ObjectAsserter (node_modules/unit.js/src/asserters/object.js:99:14)
      at UnitJS.module.exports.(anonymous function) [as object] (node_modules/unit.js/src/asserters.js:27:14)
      at Query._callback (test/test.js:183:12)
      at Query.Sequence.end (node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
      at Query._handleFinalResultPacket (node_modules/mysql/lib/protocol/sequences/Query.js:139:8)
      at Query.EofPacket (node_modules/mysql/lib/protocol/sequences/Query.js:123:8)
      at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:279:23)
      at Parser.write (node_modules/mysql/lib/protocol/Parser.js:76:12)
      at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:103:28)
      at readableAddChunk (_stream_readable.js:176:18)
      at Socket.Readable.push (_stream_readable.js:134:10)
      at Pipe.onread (net.js:547:20)

  10) MyJsql order by id and first:
     Uncaught AssertionError: undefined must be an object
      at Object.isObject (node_modules/unit.js/src/assertions.js:316:20)
      at new ObjectAsserter (node_modules/unit.js/src/asserters/object.js:99:14)
      at UnitJS.module.exports.(anonymous function) [as object] (node_modules/unit.js/src/asserters.js:27:14)
      at Query._callback (test/test.js:196:12)
      at Query.Sequence.end (node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
      at Query._handleFinalResultPacket (node_modules/mysql/lib/protocol/sequences/Query.js:139:8)
      at Query.EofPacket (node_modules/mysql/lib/protocol/sequences/Query.js:123:8)
      at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:279:23)
      at Parser.write (node_modules/mysql/lib/protocol/Parser.js:76:12)
      at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:103:28)
      at readableAddChunk (_stream_readable.js:176:18)
      at Socket.Readable.push (_stream_readable.js:134:10)
      at Pipe.onread (net.js:547:20)

  11) MyJsql limit to one:

      Uncaught AssertionError: 0 must be equivalent to 1
      + expected - actual

      -0
      +1
      
      at NumberAsserter.is (node_modules/unit.js/src/assertions.js:56:20)
      at Query._callback (test/test.js:209:29)
      at Query.Sequence.end (node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
      at Query._handleFinalResultPacket (node_modules/mysql/lib/protocol/sequences/Query.js:139:8)
      at Query.EofPacket (node_modules/mysql/lib/protocol/sequences/Query.js:123:8)
      at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:279:23)
      at Parser.write (node_modules/mysql/lib/protocol/Parser.js:76:12)
      at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:103:28)
      at readableAddChunk (_stream_readable.js:176:18)
      at Socket.Readable.push (_stream_readable.js:134:10)
      at Pipe.onread (net.js:547:20)

  12) MyJsql limit and offset by one:

      Uncaught AssertionError: 0 must be equivalent to 1
      + expected - actual

      -0
      +1
      
      at NumberAsserter.is (node_modules/unit.js/src/assertions.js:56:20)
      at Query._callback (test/test.js:222:29)
      at Query.Sequence.end (node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
      at Query._handleFinalResultPacket (node_modules/mysql/lib/protocol/sequences/Query.js:139:8)
      at Query.EofPacket (node_modules/mysql/lib/protocol/sequences/Query.js:123:8)
      at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:279:23)
      at Parser.write (node_modules/mysql/lib/protocol/Parser.js:76:12)
      at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:103:28)
      at readableAddChunk (_stream_readable.js:176:18)
      at Socket.Readable.push (_stream_readable.js:134:10)
      at Pipe.onread (net.js:547:20)

  13) MyJsql select where order by and limit:

      Uncaught AssertionError: 0 must be equivalent to 2
      + expected - actual

      -0
      +2
      
      at NumberAsserter.is (node_modules/unit.js/src/assertions.js:56:20)
      at Query._callback (test/test.js:236:29)
      at Query.Sequence.end (node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
      at Query._handleFinalResultPacket (node_modules/mysql/lib/protocol/sequences/Query.js:139:8)
      at Query.EofPacket (node_modules/mysql/lib/protocol/sequences/Query.js:123:8)
      at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:279:23)
      at Parser.write (node_modules/mysql/lib/protocol/Parser.js:76:12)
      at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:103:28)
      at readableAddChunk (_stream_readable.js:176:18)
      at Socket.Readable.push (_stream_readable.js:134:10)
      at Pipe.onread (net.js:547:20)

  14) MyJsql clear test:

      Uncaught AssertionError: 0 must be equivalent to 2
      + expected - actual

      -0
      +2
      
      at NumberAsserter.is (node_modules/unit.js/src/assertions.js:56:20)
      at Query._callback (test/test.js:250:29)
      at Query.Sequence.end (node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
      at Query._handleFinalResultPacket (node_modules/mysql/lib/protocol/sequences/Query.js:139:8)
      at Query.EofPacket (node_modules/mysql/lib/protocol/sequences/Query.js:123:8)
      at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:279:23)
      at Parser.write (node_modules/mysql/lib/protocol/Parser.js:76:12)
      at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:103:28)
      at readableAddChunk (_stream_readable.js:176:18)
      at Socket.Readable.push (_stream_readable.js:134:10)
      at Pipe.onread (net.js:547:20)

  15) MyJsql delete Jane:

      Uncaught AssertionError: 0 must be equivalent to 1
      + expected - actual

      -0
      +1
      
      at NumberAsserter.is (node_modules/unit.js/src/assertions.js:56:20)
      at Query._callback (test/test.js:263:10)
      at Query.Sequence.end (node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
      at Query._handleFinalResultPacket (node_modules/mysql/lib/protocol/sequences/Query.js:139:8)
      at Query.OkPacket (node_modules/mysql/lib/protocol/sequences/Query.js:72:10)
      at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:279:23)
      at Parser.write (node_modules/mysql/lib/protocol/Parser.js:76:12)
      at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:103:28)
      at readableAddChunk (_stream_readable.js:176:18)
      at Socket.Readable.push (_stream_readable.js:134:10)
      at Pipe.onread (net.js:547:20)

npm ERR! Test failed.  See above for more details.

npm ERR! Linux 4.10.0-35-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! my-jsql@1.5.1 build: `npm run lint; babel src --presets babel-preset-es2015 --out-dir dist --minified --no-comments; npm test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-jsql@1.5.1 build script 'npm run lint; babel src --presets babel-preset-es2015 --out-dir dist --minified --no-comments; npm test'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the my-jsql package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run lint; babel src --presets babel-preset-es2015 --out-dir dist --minified --no-comments; npm test
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs my-jsql
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls my-jsql
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/anibal/my-jsql/npm-debug.log
anibal@LENOVO:~/my-jsql$

**Comment by z3nz** [comment]
@ademon82 what version of node are you using?

**Comment by z3nz** [comment]
@ademon82 try pulling down the latest. I updated the babel preset and added polyfills, so it should work now.

**Comment by ghost** [comment]
anibal@LENOVO:~/Descargas$ node -v
v6.11.3

2017-09-29 15:47 GMT+02:00 Adam Lynch <notifications@github.com>:

**Comment by ghost** [comment]
OK, now it just fails the "npm test" rest ok

---

anibal@LENOVO:~/Descargas/my-jsql-master$ npm test

> my-jsql@1.5.2 test /home/anibal/Descargas/my-jsql-master
> mocha test

module.js:471
    throw err;
    ^

Error: Cannot find module '../dist/index.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous>
(/home/anibal/Descargas/my-jsql-master/test/test.js:2:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at
/home/anibal/Descargas/my-jsql-master/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (native)
    at Mocha.loadFiles
(/home/anibal/Descargas/my-jsql-master/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run
(/home/anibal/Descargas/my-jsql-master/node_modules/mocha/lib/mocha.js:514:10)
    at Object.<anonymous>
(/home/anibal/Descargas/my-jsql-master/node_modules/mocha/bin/_mocha:480:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:502:3
npm ERR! Test failed.  See above for more details.
anibal@LENOVO:~/Descargas/my-jsql-master$ npm run build

> my-jsql@1.5.2 build /home/anibal/Descargas/my-jsql-master
> npm run lint; babel src --out-dir dist --minified --no-comments; npm test


> my-jsql@1.5.2 lint /home/anibal/Descargas/my-jsql-master
> eslint src -c .eslintrc.js; eslint test -c .eslintrc.js

src/index.js -> dist/index.js
src/lib/MyJsql.js -> dist/lib/MyJsql.js

> my-jsql@1.5.2 test /home/anibal/Descargas/my-jsql-master
> mocha test



  MyJsql
    ✓ assertions (57ms)
    ✓ start (49ms)
    ✓ create db
    ✓ use db
    ✓ create table (318ms)
    ✓ set table
    ✓ insert John Doe (88ms)
    ✓ insert Jane Doe (72ms)
    ✓ select John (60ms)
    ✓ select only one key
    ✓ select John and Jane
    ✓ where condition as string
    ✓ select John or Jane
    ✓ update John to Jack (75ms)
    ✓ order by first
    ✓ order by id and first
    ✓ limit to one (42ms)
    ✓ limit and offset by one
    ✓ select where order by and limit
    ✓ clear test
    ✓ delete Jane (39ms)
    ✓ drop db (236ms)
    ✓ stop


  23 passing (1s)

anibal@LENOVO:~/Descargas/my-jsql-master$


2017-09-29 15:54 GMT+02:00 Anibal Alvarez Alvarez <
ani.alvarez.alvarez@gmail.com>:

**Comment by z3nz** [comment]
Try running it again, it looks like you ran `npm test` before `npm run build` so there were no build files to test. When you ran build, it ran `npm test` and it worked fine:

>  ***@***.*** test /home/anibal/Descargas/my-jsql-master
 mocha test
MyJsql
    ✓ assertions (57ms)
    ✓ start (49ms)
    ✓ create db
    ✓ use db
    ✓ create table (318ms)
    ✓ set table
    ✓ insert John Doe (88ms)
    ✓ insert Jane Doe (72ms)
    ✓ select John (60ms)
    ✓ select only one key
    ✓ select John and Jane
    ✓ where condition as string
    ✓ select John or Jane
    ✓ update John to Jack (75ms)
    ✓ order by first
    ✓ order by id and first
    ✓ limit to one (42ms)
    ✓ limit and offset by one
    ✓ select where order by and limit
    ✓ clear test
    ✓ delete Jane (39ms)
    ✓ drop db (236ms)
    ✓ stop


  23 passing (1s)

**Comment by ghost** [comment]
ALL OK now. And I need some help from you, I'll setup keybase to chat with
you if you want to help me to implement your library. Would you help me?

anibal@LENOVO:~/Descargas/my-jsql-master$ npm test

> my-jsql@1.5.2 test /home/anibal/Descargas/my-jsql-master
> mocha test



  MyJsql
    ✓ assertions (60ms)
    ✓ start (58ms)
    ✓ create db
    ✓ use db
    ✓ create table (471ms)
    ✓ set table
    ✓ insert John Doe (95ms)
    ✓ insert Jane Doe (115ms)
    ✓ select John
    ✓ select only one key
    ✓ select John and Jane
    ✓ where condition as string
    ✓ select John or Jane
    ✓ update John to Jack (113ms)
    ✓ order by first
    ✓ order by id and first
    ✓ limit to one
    ✓ limit and offset by one
    ✓ select where order by and limit (89ms)
    ✓ clear test
    ✓ delete Jane (75ms)
    ✓ drop db (371ms)
    ✓ stop


  23 passing (2s)

anibal@LENOVO:~/Descargas/my-jsql-master$


2017-09-29 16:15 GMT+02:00 Adam Lynch <notifications@github.com>:

**Comment by z3nz** [comment]
I don't have the time right now, but I'm happy to answer any questions you have. The [README](https://github.com/z3nz/my-jsql/blob/master/README.md) should cover pretty much everything, but I'll try to help as much as I can. I'm also going to close this now.
